// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: proto/admin.proto

package proto

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model metadata
type ModelInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	App                 string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VerboseName         string                 `protobuf:"bytes,3,opt,name=verbose_name,json=verboseName,proto3" json:"verbose_name,omitempty"`
	VerboseNamePlural   string                 `protobuf:"bytes,4,opt,name=verbose_name_plural,json=verboseNamePlural,proto3" json:"verbose_name_plural,omitempty"`
	ListDisplay         []string               `protobuf:"bytes,5,rep,name=list_display,json=listDisplay,proto3" json:"list_display,omitempty"`
	SearchFields        []string               `protobuf:"bytes,6,rep,name=search_fields,json=searchFields,proto3" json:"search_fields,omitempty"`
	ListFilter          []string               `protobuf:"bytes,7,rep,name=list_filter,json=listFilter,proto3" json:"list_filter,omitempty"`
	ReadonlyFields      []string               `protobuf:"bytes,8,rep,name=readonly_fields,json=readonlyFields,proto3" json:"readonly_fields,omitempty"`
	Exclude             []string               `protobuf:"bytes,9,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Permissions         *ModelPermissions      `protobuf:"bytes,10,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Actions             []*AdminAction         `protobuf:"bytes,11,rep,name=actions,proto3" json:"actions,omitempty"`
	ListPerPage         int32                  `protobuf:"varint,12,opt,name=list_per_page,json=listPerPage,proto3" json:"list_per_page,omitempty"`
	Ordering            string                 `protobuf:"bytes,13,opt,name=ordering,proto3" json:"ordering,omitempty"`
	ShowFullResultCount bool                   `protobuf:"varint,14,opt,name=show_full_result_count,json=showFullResultCount,proto3" json:"show_full_result_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ModelInfo) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetVerboseName() string {
	if x != nil {
		return x.VerboseName
	}
	return ""
}

func (x *ModelInfo) GetVerboseNamePlural() string {
	if x != nil {
		return x.VerboseNamePlural
	}
	return ""
}

func (x *ModelInfo) GetListDisplay() []string {
	if x != nil {
		return x.ListDisplay
	}
	return nil
}

func (x *ModelInfo) GetSearchFields() []string {
	if x != nil {
		return x.SearchFields
	}
	return nil
}

func (x *ModelInfo) GetListFilter() []string {
	if x != nil {
		return x.ListFilter
	}
	return nil
}

func (x *ModelInfo) GetReadonlyFields() []string {
	if x != nil {
		return x.ReadonlyFields
	}
	return nil
}

func (x *ModelInfo) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *ModelInfo) GetPermissions() *ModelPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ModelInfo) GetActions() []*AdminAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ModelInfo) GetListPerPage() int32 {
	if x != nil {
		return x.ListPerPage
	}
	return 0
}

func (x *ModelInfo) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *ModelInfo) GetShowFullResultCount() bool {
	if x != nil {
		return x.ShowFullResultCount
	}
	return false
}

type ModelPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           bool                   `protobuf:"varint,1,opt,name=add,proto3" json:"add,omitempty"`
	Change        bool                   `protobuf:"varint,2,opt,name=change,proto3" json:"change,omitempty"`
	Delete        bool                   `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	View          bool                   `protobuf:"varint,4,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelPermissions) Reset() {
	*x = ModelPermissions{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPermissions) ProtoMessage() {}

func (x *ModelPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPermissions.ProtoReflect.Descriptor instead.
func (*ModelPermissions) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ModelPermissions) GetAdd() bool {
	if x != nil {
		return x.Add
	}
	return false
}

func (x *ModelPermissions) GetChange() bool {
	if x != nil {
		return x.Change
	}
	return false
}

func (x *ModelPermissions) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

func (x *ModelPermissions) GetView() bool {
	if x != nil {
		return x.View
	}
	return false
}

type AdminAction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ConfirmationRequired bool                   `protobuf:"varint,3,opt,name=confirmation_required,json=confirmationRequired,proto3" json:"confirmation_required,omitempty"`
	Permissions          []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AdminAction) Reset() {
	*x = AdminAction{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAction) ProtoMessage() {}

func (x *AdminAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAction.ProtoReflect.Descriptor instead.
func (*AdminAction) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminAction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminAction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminAction) GetConfirmationRequired() bool {
	if x != nil {
		return x.ConfirmationRequired
	}
	return false
}

func (x *AdminAction) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Field metadata for forms and display
type FieldInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FieldType     string                 `protobuf:"bytes,2,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	VerboseName   string                 `protobuf:"bytes,3,opt,name=verbose_name,json=verboseName,proto3" json:"verbose_name,omitempty"`
	HelpText      string                 `protobuf:"bytes,4,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Editable      bool                   `protobuf:"varint,6,opt,name=editable,proto3" json:"editable,omitempty"`
	Blank         bool                   `protobuf:"varint,7,opt,name=blank,proto3" json:"blank,omitempty"`
	Null          bool                   `protobuf:"varint,8,opt,name=null,proto3" json:"null,omitempty"`
	DefaultValue  *any1.Any              `protobuf:"bytes,9,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Choices       []string               `protobuf:"bytes,10,rep,name=choices,proto3" json:"choices,omitempty"`
	MaxLength     int32                  `protobuf:"varint,11,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Unique        bool                   `protobuf:"varint,12,opt,name=unique,proto3" json:"unique,omitempty"`
	RelatedModel  string                 `protobuf:"bytes,13,opt,name=related_model,json=relatedModel,proto3" json:"related_model,omitempty"`
	WidgetType    string                 `protobuf:"bytes,14,opt,name=widget_type,json=widgetType,proto3" json:"widget_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldInfo) Reset() {
	*x = FieldInfo{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldInfo) ProtoMessage() {}

func (x *FieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldInfo.ProtoReflect.Descriptor instead.
func (*FieldInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *FieldInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldInfo) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *FieldInfo) GetVerboseName() string {
	if x != nil {
		return x.VerboseName
	}
	return ""
}

func (x *FieldInfo) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

func (x *FieldInfo) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldInfo) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *FieldInfo) GetBlank() bool {
	if x != nil {
		return x.Blank
	}
	return false
}

func (x *FieldInfo) GetNull() bool {
	if x != nil {
		return x.Null
	}
	return false
}

func (x *FieldInfo) GetDefaultValue() *any1.Any {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *FieldInfo) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *FieldInfo) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *FieldInfo) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *FieldInfo) GetRelatedModel() string {
	if x != nil {
		return x.RelatedModel
	}
	return ""
}

func (x *FieldInfo) GetWidgetType() string {
	if x != nil {
		return x.WidgetType
	}
	return ""
}

// Requests and responses
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        map[string]*ModelInfo  `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Site          *SiteInfo              `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsResponse) GetModels() map[string]*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetSite() *SiteInfo {
	if x != nil {
		return x.Site
	}
	return nil
}

type SiteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HeaderTitle   string                 `protobuf:"bytes,2,opt,name=header_title,json=headerTitle,proto3" json:"header_title,omitempty"`
	IndexTitle    string                 `protobuf:"bytes,3,opt,name=index_title,json=indexTitle,proto3" json:"index_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteInfo) Reset() {
	*x = SiteInfo{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteInfo) ProtoMessage() {}

func (x *SiteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteInfo.ProtoReflect.Descriptor instead.
func (*SiteInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *SiteInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SiteInfo) GetHeaderTitle() string {
	if x != nil {
		return x.HeaderTitle
	}
	return ""
}

func (x *SiteInfo) GetIndexTitle() string {
	if x != nil {
		return x.IndexTitle
	}
	return ""
}

type GetModelSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelSchemaRequest) Reset() {
	*x = GetModelSchemaRequest{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelSchemaRequest) ProtoMessage() {}

func (x *GetModelSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetModelSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetModelSchemaRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *GetModelSchemaRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetModelSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelInfo     *ModelInfo             `protobuf:"bytes,1,opt,name=model_info,json=modelInfo,proto3" json:"model_info,omitempty"`
	Fields        []*FieldInfo           `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelSchemaResponse) Reset() {
	*x = GetModelSchemaResponse{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelSchemaResponse) ProtoMessage() {}

func (x *GetModelSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetModelSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetModelSchemaResponse) GetModelInfo() *ModelInfo {
	if x != nil {
		return x.ModelInfo
	}
	return nil
}

func (x *GetModelSchemaResponse) GetFields() []*FieldInfo {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Ordering      string                 `protobuf:"bytes,5,opt,name=ordering,proto3" json:"ordering,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Search        string                 `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListObjectsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListObjectsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListObjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListObjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListObjectsRequest) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *ListObjectsRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListObjectsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectData          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,6,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	TotalPages    int32                  `protobuf:"varint,7,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	DisplayFields []string               `protobuf:"bytes,8,rep,name=display_fields,json=displayFields,proto3" json:"display_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListObjectsResponse) GetObjects() []*ObjectData {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListObjectsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListObjectsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListObjectsResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *ListObjectsResponse) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *ListObjectsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListObjectsResponse) GetDisplayFields() []string {
	if x != nil {
		return x.DisplayFields
	}
	return nil
}

type ObjectData struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Id                string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields            map[string]*_struct.Value `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StrRepresentation string                    `protobuf:"bytes,3,opt,name=str_representation,json=strRepresentation,proto3" json:"str_representation,omitempty"`
	CreatedAt         *timestamp.Timestamp      `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamp.Timestamp      `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ObjectData) Reset() {
	*x = ObjectData{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectData) ProtoMessage() {}

func (x *ObjectData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectData.ProtoReflect.Descriptor instead.
func (*ObjectData) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectData) GetFields() map[string]*_struct.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ObjectData) GetStrRepresentation() string {
	if x != nil {
		return x.StrRepresentation
	}
	return ""
}

func (x *ObjectData) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectData) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetObjectRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *GetObjectRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectData            `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	FormFields    []*FieldInfo           `protobuf:"bytes,2,rep,name=form_fields,json=formFields,proto3" json:"form_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GetObjectResponse) GetObject() *ObjectData {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GetObjectResponse) GetFormFields() []*FieldInfo {
	if x != nil {
		return x.FormFields
	}
	return nil
}

type CreateObjectRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	App           string                    `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Data          map[string]*_struct.Value `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObjectRequest) Reset() {
	*x = CreateObjectRequest{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectRequest) ProtoMessage() {}

func (x *CreateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectRequest.ProtoReflect.Descriptor instead.
func (*CreateObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *CreateObjectRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CreateObjectRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateObjectRequest) GetData() map[string]*_struct.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectData            `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObjectResponse) Reset() {
	*x = CreateObjectResponse{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectResponse) ProtoMessage() {}

func (x *CreateObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectResponse.ProtoReflect.Descriptor instead.
func (*CreateObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *CreateObjectResponse) GetObject() *ObjectData {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CreateObjectResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CreateObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateObjectRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	App           string                    `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Id            string                    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data          map[string]*_struct.Value `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObjectRequest) Reset() {
	*x = UpdateObjectRequest{}
	mi := &file_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectRequest) ProtoMessage() {}

func (x *UpdateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateObjectRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *UpdateObjectRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateObjectRequest) GetData() map[string]*_struct.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *ObjectData            `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObjectResponse) Reset() {
	*x = UpdateObjectResponse{}
	mi := &file_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectResponse) ProtoMessage() {}

func (x *UpdateObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateObjectResponse) GetObject() *ObjectData {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *UpdateObjectResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *UpdateObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteObjectRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *DeleteObjectRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeleteObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteObjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectsRequest) Reset() {
	*x = DeleteObjectsRequest{}
	mi := &file_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectsRequest) ProtoMessage() {}

func (x *DeleteObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectsRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteObjectsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *DeleteObjectsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeleteObjectsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectsResponse) Reset() {
	*x = DeleteObjectsResponse{}
	mi := &file_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectsResponse) ProtoMessage() {}

func (x *DeleteObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectsResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteObjectsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteObjectsResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

func (x *DeleteObjectsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteObjectsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	App           string                    `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Action        string                    `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ObjectIds     []string                  `protobuf:"bytes,4,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	Parameters    map[string]*_struct.Value `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ExecuteActionRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ExecuteActionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecuteActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteActionRequest) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *ExecuteActionRequest) GetParameters() map[string]*_struct.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AffectedCount int32                  `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ExecuteActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteActionResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

func (x *ExecuteActionResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ListActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsRequest) Reset() {
	*x = ListActionsRequest{}
	mi := &file_proto_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsRequest) ProtoMessage() {}

func (x *ListActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ListActionsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListActionsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ListActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*AdminAction         `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsResponse) Reset() {
	*x = ListActionsResponse{}
	mi := &file_proto_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsResponse) ProtoMessage() {}

func (x *ListActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ListActionsResponse) GetActions() []*AdminAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type SearchObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchObjectsRequest) Reset() {
	*x = SearchObjectsRequest{}
	mi := &file_proto_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchObjectsRequest) ProtoMessage() {}

func (x *SearchObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchObjectsRequest.ProtoReflect.Descriptor instead.
func (*SearchObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{26}
}

func (x *SearchObjectsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *SearchObjectsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SearchObjectsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchObjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectData          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchObjectsResponse) Reset() {
	*x = SearchObjectsResponse{}
	mi := &file_proto_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchObjectsResponse) ProtoMessage() {}

func (x *SearchObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchObjectsResponse.ProtoReflect.Descriptor instead.
func (*SearchObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{27}
}

func (x *SearchObjectsResponse) GetObjects() []*ObjectData {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *SearchObjectsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_proto_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Filter types for advanced filtering
type FilterOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOption) Reset() {
	*x = FilterOption{}
	mi := &file_proto_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOption) ProtoMessage() {}

func (x *FilterOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOption.ProtoReflect.Descriptor instead.
func (*FilterOption) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{29}
}

func (x *FilterOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FilterOption) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FilterSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	LookupType    string                 `protobuf:"bytes,2,opt,name=lookup_type,json=lookupType,proto3" json:"lookup_type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Options       []*FilterOption        `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterSpec) Reset() {
	*x = FilterSpec{}
	mi := &file_proto_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterSpec) ProtoMessage() {}

func (x *FilterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterSpec.ProtoReflect.Descriptor instead.
func (*FilterSpec) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{30}
}

func (x *FilterSpec) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterSpec) GetLookupType() string {
	if x != nil {
		return x.LookupType
	}
	return ""
}

func (x *FilterSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FilterSpec) GetOptions() []*FilterOption {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\rgojango.admin\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x04\n" +
	"\tModelInfo\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fverbose_name\x18\x03 \x01(\tR\vverboseName\x12.\n" +
	"\x13verbose_name_plural\x18\x04 \x01(\tR\x11verboseNamePlural\x12!\n" +
	"\flist_display\x18\x05 \x03(\tR\vlistDisplay\x12#\n" +
	"\rsearch_fields\x18\x06 \x03(\tR\fsearchFields\x12\x1f\n" +
	"\vlist_filter\x18\a \x03(\tR\n" +
	"listFilter\x12'\n" +
	"\x0freadonly_fields\x18\b \x03(\tR\x0ereadonlyFields\x12\x18\n" +
	"\aexclude\x18\t \x03(\tR\aexclude\x12A\n" +
	"\vpermissions\x18\n" +
	" \x01(\v2\x1f.gojango.admin.ModelPermissionsR\vpermissions\x124\n" +
	"\aactions\x18\v \x03(\v2\x1a.gojango.admin.AdminActionR\aactions\x12\"\n" +
	"\rlist_per_page\x18\f \x01(\x05R\vlistPerPage\x12\x1a\n" +
	"\bordering\x18\r \x01(\tR\bordering\x123\n" +
	"\x16show_full_result_count\x18\x0e \x01(\bR\x13showFullResultCount\"h\n" +
	"\x10ModelPermissions\x12\x10\n" +
	"\x03add\x18\x01 \x01(\bR\x03add\x12\x16\n" +
	"\x06change\x18\x02 \x01(\bR\x06change\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\bR\x06delete\x12\x12\n" +
	"\x04view\x18\x04 \x01(\bR\x04view\"\x9a\x01\n" +
	"\vAdminAction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\x15confirmation_required\x18\x03 \x01(\bR\x14confirmationRequired\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"\xb2\x03\n" +
	"\tFieldInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"field_type\x18\x02 \x01(\tR\tfieldType\x12!\n" +
	"\fverbose_name\x18\x03 \x01(\tR\vverboseName\x12\x1b\n" +
	"\thelp_text\x18\x04 \x01(\tR\bhelpText\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\beditable\x18\x06 \x01(\bR\beditable\x12\x14\n" +
	"\x05blank\x18\a \x01(\bR\x05blank\x12\x12\n" +
	"\x04null\x18\b \x01(\bR\x04null\x129\n" +
	"\rdefault_value\x18\t \x01(\v2\x14.google.protobuf.AnyR\fdefaultValue\x12\x18\n" +
	"\achoices\x18\n" +
	" \x03(\tR\achoices\x12\x1d\n" +
	"\n" +
	"max_length\x18\v \x01(\x05R\tmaxLength\x12\x16\n" +
	"\x06unique\x18\f \x01(\bR\x06unique\x12#\n" +
	"\rrelated_model\x18\r \x01(\tR\frelatedModel\x12\x1f\n" +
	"\vwidget_type\x18\x0e \x01(\tR\n" +
	"widgetType\"\x13\n" +
	"\x11ListModelsRequest\"\xdd\x01\n" +
	"\x12ListModelsResponse\x12E\n" +
	"\x06models\x18\x01 \x03(\v2-.gojango.admin.ListModelsResponse.ModelsEntryR\x06models\x12+\n" +
	"\x04site\x18\x02 \x01(\v2\x17.gojango.admin.SiteInfoR\x04site\x1aS\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.gojango.admin.ModelInfoR\x05value:\x028\x01\"b\n" +
	"\bSiteInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fheader_title\x18\x02 \x01(\tR\vheaderTitle\x12\x1f\n" +
	"\vindex_title\x18\x03 \x01(\tR\n" +
	"indexTitle\"?\n" +
	"\x15GetModelSchemaRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"\x83\x01\n" +
	"\x16GetModelSchemaResponse\x127\n" +
	"\n" +
	"model_info\x18\x01 \x01(\v2\x18.gojango.admin.ModelInfoR\tmodelInfo\x120\n" +
	"\x06fields\x18\x02 \x03(\v2\x18.gojango.admin.FieldInfoR\x06fields\"\xa7\x02\n" +
	"\x12ListObjectsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bordering\x18\x05 \x01(\tR\bordering\x12H\n" +
	"\afilters\x18\x06 \x03(\v2..gojango.admin.ListObjectsRequest.FiltersEntryR\afilters\x12\x16\n" +
	"\x06search\x18\a \x01(\tR\x06search\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\x13ListObjectsResponse\x123\n" +
	"\aobjects\x18\x01 \x03(\v2\x19.gojango.admin.ObjectDataR\aobjects\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x06 \x01(\bR\vhasPrevious\x12\x1f\n" +
	"\vtotal_pages\x18\a \x01(\x05R\n" +
	"totalPages\x12%\n" +
	"\x0edisplay_fields\x18\b \x03(\tR\rdisplayFields\"\xd3\x02\n" +
	"\n" +
	"ObjectData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x06fields\x18\x02 \x03(\v2%.gojango.admin.ObjectData.FieldsEntryR\x06fields\x12-\n" +
	"\x12str_representation\x18\x03 \x01(\tR\x11strRepresentation\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"J\n" +
	"\x10GetObjectRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\x81\x01\n" +
	"\x11GetObjectResponse\x121\n" +
	"\x06object\x18\x01 \x01(\v2\x19.gojango.admin.ObjectDataR\x06object\x129\n" +
	"\vform_fields\x18\x02 \x03(\v2\x18.gojango.admin.FieldInfoR\n" +
	"formFields\"\xd0\x01\n" +
	"\x13CreateObjectRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12@\n" +
	"\x04data\x18\x03 \x03(\v2,.gojango.admin.CreateObjectRequest.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x14CreateObjectResponse\x121\n" +
	"\x06object\x18\x01 \x01(\v2\x19.gojango.admin.ObjectDataR\x06object\x126\n" +
	"\x06errors\x18\x02 \x03(\v2\x1e.gojango.admin.ValidationErrorR\x06errors\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xe0\x01\n" +
	"\x13UpdateObjectRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12@\n" +
	"\x04data\x18\x04 \x03(\v2,.gojango.admin.UpdateObjectRequest.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x14UpdateObjectResponse\x121\n" +
	"\x06object\x18\x01 \x01(\v2\x19.gojango.admin.ObjectDataR\x06object\x126\n" +
	"\x06errors\x18\x02 \x03(\v2\x1e.gojango.admin.ValidationErrorR\x06errors\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"M\n" +
	"\x13DeleteObjectRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"J\n" +
	"\x14DeleteObjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"P\n" +
	"\x14DeleteObjectsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"\x8f\x01\n" +
	"\x15DeleteObjectsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xa1\x02\n" +
	"\x14ExecuteActionRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x04 \x03(\tR\tobjectIds\x12S\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v23.gojango.admin.ExecuteActionRequest.ParametersEntryR\n" +
	"parameters\x1aU\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x15ExecuteActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\x05R\raffectedCount\x126\n" +
	"\x06errors\x18\x04 \x03(\v2\x1e.gojango.admin.ValidationErrorR\x06errors\"<\n" +
	"\x12ListActionsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"K\n" +
	"\x13ListActionsResponse\x124\n" +
	"\aactions\x18\x01 \x03(\v2\x1a.gojango.admin.AdminActionR\aactions\"j\n" +
	"\x14SearchObjectsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"m\n" +
	"\x15SearchObjectsResponse\x123\n" +
	"\aobjects\x18\x01 \x03(\v2\x19.gojango.admin.ObjectDataR\aobjects\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"U\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"N\n" +
	"\fFilterOption\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x90\x01\n" +
	"\n" +
	"FilterSpec\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1f\n" +
	"\vlookup_type\x18\x02 \x01(\tR\n" +
	"lookupType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x125\n" +
	"\aoptions\x18\x04 \x03(\v2\x1b.gojango.admin.FilterOptionR\aoptions2\xdb\a\n" +
	"\fAdminService\x12Q\n" +
	"\n" +
	"ListModels\x12 .gojango.admin.ListModelsRequest\x1a!.gojango.admin.ListModelsResponse\x12]\n" +
	"\x0eGetModelSchema\x12$.gojango.admin.GetModelSchemaRequest\x1a%.gojango.admin.GetModelSchemaResponse\x12T\n" +
	"\vListObjects\x12!.gojango.admin.ListObjectsRequest\x1a\".gojango.admin.ListObjectsResponse\x12N\n" +
	"\tGetObject\x12\x1f.gojango.admin.GetObjectRequest\x1a .gojango.admin.GetObjectResponse\x12W\n" +
	"\fCreateObject\x12\".gojango.admin.CreateObjectRequest\x1a#.gojango.admin.CreateObjectResponse\x12W\n" +
	"\fUpdateObject\x12\".gojango.admin.UpdateObjectRequest\x1a#.gojango.admin.UpdateObjectResponse\x12W\n" +
	"\fDeleteObject\x12\".gojango.admin.DeleteObjectRequest\x1a#.gojango.admin.DeleteObjectResponse\x12Z\n" +
	"\rDeleteObjects\x12#.gojango.admin.DeleteObjectsRequest\x1a$.gojango.admin.DeleteObjectsResponse\x12Z\n" +
	"\rExecuteAction\x12#.gojango.admin.ExecuteActionRequest\x1a$.gojango.admin.ExecuteActionResponse\x12T\n" +
	"\vListActions\x12!.gojango.admin.ListActionsRequest\x1a\".gojango.admin.ListActionsResponse\x12Z\n" +
	"\rSearchObjects\x12#.gojango.admin.SearchObjectsRequest\x1a$.gojango.admin.SearchObjectsResponseB5Z3github.com/epuerta9/gojango/pkg/gojango/admin/protob\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_admin_proto_goTypes = []any{
	(*ModelInfo)(nil),              // 0: gojango.admin.ModelInfo
	(*ModelPermissions)(nil),       // 1: gojango.admin.ModelPermissions
	(*AdminAction)(nil),            // 2: gojango.admin.AdminAction
	(*FieldInfo)(nil),              // 3: gojango.admin.FieldInfo
	(*ListModelsRequest)(nil),      // 4: gojango.admin.ListModelsRequest
	(*ListModelsResponse)(nil),     // 5: gojango.admin.ListModelsResponse
	(*SiteInfo)(nil),               // 6: gojango.admin.SiteInfo
	(*GetModelSchemaRequest)(nil),  // 7: gojango.admin.GetModelSchemaRequest
	(*GetModelSchemaResponse)(nil), // 8: gojango.admin.GetModelSchemaResponse
	(*ListObjectsRequest)(nil),     // 9: gojango.admin.ListObjectsRequest
	(*ListObjectsResponse)(nil),    // 10: gojango.admin.ListObjectsResponse
	(*ObjectData)(nil),             // 11: gojango.admin.ObjectData
	(*GetObjectRequest)(nil),       // 12: gojango.admin.GetObjectRequest
	(*GetObjectResponse)(nil),      // 13: gojango.admin.GetObjectResponse
	(*CreateObjectRequest)(nil),    // 14: gojango.admin.CreateObjectRequest
	(*CreateObjectResponse)(nil),   // 15: gojango.admin.CreateObjectResponse
	(*UpdateObjectRequest)(nil),    // 16: gojango.admin.UpdateObjectRequest
	(*UpdateObjectResponse)(nil),   // 17: gojango.admin.UpdateObjectResponse
	(*DeleteObjectRequest)(nil),    // 18: gojango.admin.DeleteObjectRequest
	(*DeleteObjectResponse)(nil),   // 19: gojango.admin.DeleteObjectResponse
	(*DeleteObjectsRequest)(nil),   // 20: gojango.admin.DeleteObjectsRequest
	(*DeleteObjectsResponse)(nil),  // 21: gojango.admin.DeleteObjectsResponse
	(*ExecuteActionRequest)(nil),   // 22: gojango.admin.ExecuteActionRequest
	(*ExecuteActionResponse)(nil),  // 23: gojango.admin.ExecuteActionResponse
	(*ListActionsRequest)(nil),     // 24: gojango.admin.ListActionsRequest
	(*ListActionsResponse)(nil),    // 25: gojango.admin.ListActionsResponse
	(*SearchObjectsRequest)(nil),   // 26: gojango.admin.SearchObjectsRequest
	(*SearchObjectsResponse)(nil),  // 27: gojango.admin.SearchObjectsResponse
	(*ValidationError)(nil),        // 28: gojango.admin.ValidationError
	(*FilterOption)(nil),           // 29: gojango.admin.FilterOption
	(*FilterSpec)(nil),             // 30: gojango.admin.FilterSpec
	nil,                            // 31: gojango.admin.ListModelsResponse.ModelsEntry
	nil,                            // 32: gojango.admin.ListObjectsRequest.FiltersEntry
	nil,                            // 33: gojango.admin.ObjectData.FieldsEntry
	nil,                            // 34: gojango.admin.CreateObjectRequest.DataEntry
	nil,                            // 35: gojango.admin.UpdateObjectRequest.DataEntry
	nil,                            // 36: gojango.admin.ExecuteActionRequest.ParametersEntry
	(*any1.Any)(nil),               // 37: google.protobuf.Any
	(*timestamp.Timestamp)(nil),    // 38: google.protobuf.Timestamp
	(*_struct.Value)(nil),          // 39: google.protobuf.Value
}
var file_proto_admin_proto_depIdxs = []int32{
	1,  // 0: gojango.admin.ModelInfo.permissions:type_name -> gojango.admin.ModelPermissions
	2,  // 1: gojango.admin.ModelInfo.actions:type_name -> gojango.admin.AdminAction
	37, // 2: gojango.admin.FieldInfo.default_value:type_name -> google.protobuf.Any
	31, // 3: gojango.admin.ListModelsResponse.models:type_name -> gojango.admin.ListModelsResponse.ModelsEntry
	6,  // 4: gojango.admin.ListModelsResponse.site:type_name -> gojango.admin.SiteInfo
	0,  // 5: gojango.admin.GetModelSchemaResponse.model_info:type_name -> gojango.admin.ModelInfo
	3,  // 6: gojango.admin.GetModelSchemaResponse.fields:type_name -> gojango.admin.FieldInfo
	32, // 7: gojango.admin.ListObjectsRequest.filters:type_name -> gojango.admin.ListObjectsRequest.FiltersEntry
	11, // 8: gojango.admin.ListObjectsResponse.objects:type_name -> gojango.admin.ObjectData
	33, // 9: gojango.admin.ObjectData.fields:type_name -> gojango.admin.ObjectData.FieldsEntry
	38, // 10: gojango.admin.ObjectData.created_at:type_name -> google.protobuf.Timestamp
	38, // 11: gojango.admin.ObjectData.updated_at:type_name -> google.protobuf.Timestamp
	11, // 12: gojango.admin.GetObjectResponse.object:type_name -> gojango.admin.ObjectData
	3,  // 13: gojango.admin.GetObjectResponse.form_fields:type_name -> gojango.admin.FieldInfo
	34, // 14: gojango.admin.CreateObjectRequest.data:type_name -> gojango.admin.CreateObjectRequest.DataEntry
	11, // 15: gojango.admin.CreateObjectResponse.object:type_name -> gojango.admin.ObjectData
	28, // 16: gojango.admin.CreateObjectResponse.errors:type_name -> gojango.admin.ValidationError
	35, // 17: gojango.admin.UpdateObjectRequest.data:type_name -> gojango.admin.UpdateObjectRequest.DataEntry
	11, // 18: gojango.admin.UpdateObjectResponse.object:type_name -> gojango.admin.ObjectData
	28, // 19: gojango.admin.UpdateObjectResponse.errors:type_name -> gojango.admin.ValidationError
	36, // 20: gojango.admin.ExecuteActionRequest.parameters:type_name -> gojango.admin.ExecuteActionRequest.ParametersEntry
	28, // 21: gojango.admin.ExecuteActionResponse.errors:type_name -> gojango.admin.ValidationError
	2,  // 22: gojango.admin.ListActionsResponse.actions:type_name -> gojango.admin.AdminAction
	11, // 23: gojango.admin.SearchObjectsResponse.objects:type_name -> gojango.admin.ObjectData
	29, // 24: gojango.admin.FilterSpec.options:type_name -> gojango.admin.FilterOption
	0,  // 25: gojango.admin.ListModelsResponse.ModelsEntry.value:type_name -> gojango.admin.ModelInfo
	39, // 26: gojango.admin.ObjectData.FieldsEntry.value:type_name -> google.protobuf.Value
	39, // 27: gojango.admin.CreateObjectRequest.DataEntry.value:type_name -> google.protobuf.Value
	39, // 28: gojango.admin.UpdateObjectRequest.DataEntry.value:type_name -> google.protobuf.Value
	39, // 29: gojango.admin.ExecuteActionRequest.ParametersEntry.value:type_name -> google.protobuf.Value
	4,  // 30: gojango.admin.AdminService.ListModels:input_type -> gojango.admin.ListModelsRequest
	7,  // 31: gojango.admin.AdminService.GetModelSchema:input_type -> gojango.admin.GetModelSchemaRequest
	9,  // 32: gojango.admin.AdminService.ListObjects:input_type -> gojango.admin.ListObjectsRequest
	12, // 33: gojango.admin.AdminService.GetObject:input_type -> gojango.admin.GetObjectRequest
	14, // 34: gojango.admin.AdminService.CreateObject:input_type -> gojango.admin.CreateObjectRequest
	16, // 35: gojango.admin.AdminService.UpdateObject:input_type -> gojango.admin.UpdateObjectRequest
	18, // 36: gojango.admin.AdminService.DeleteObject:input_type -> gojango.admin.DeleteObjectRequest
	20, // 37: gojango.admin.AdminService.DeleteObjects:input_type -> gojango.admin.DeleteObjectsRequest
	22, // 38: gojango.admin.AdminService.ExecuteAction:input_type -> gojango.admin.ExecuteActionRequest
	24, // 39: gojango.admin.AdminService.ListActions:input_type -> gojango.admin.ListActionsRequest
	26, // 40: gojango.admin.AdminService.SearchObjects:input_type -> gojango.admin.SearchObjectsRequest
	5,  // 41: gojango.admin.AdminService.ListModels:output_type -> gojango.admin.ListModelsResponse
	8,  // 42: gojango.admin.AdminService.GetModelSchema:output_type -> gojango.admin.GetModelSchemaResponse
	10, // 43: gojango.admin.AdminService.ListObjects:output_type -> gojango.admin.ListObjectsResponse
	13, // 44: gojango.admin.AdminService.GetObject:output_type -> gojango.admin.GetObjectResponse
	15, // 45: gojango.admin.AdminService.CreateObject:output_type -> gojango.admin.CreateObjectResponse
	17, // 46: gojango.admin.AdminService.UpdateObject:output_type -> gojango.admin.UpdateObjectResponse
	19, // 47: gojango.admin.AdminService.DeleteObject:output_type -> gojango.admin.DeleteObjectResponse
	21, // 48: gojango.admin.AdminService.DeleteObjects:output_type -> gojango.admin.DeleteObjectsResponse
	23, // 49: gojango.admin.AdminService.ExecuteAction:output_type -> gojango.admin.ExecuteActionResponse
	25, // 50: gojango.admin.AdminService.ListActions:output_type -> gojango.admin.ListActionsResponse
	27, // 51: gojango.admin.AdminService.SearchObjects:output_type -> gojango.admin.SearchObjectsResponse
	41, // [41:52] is the sub-list for method output_type
	30, // [30:41] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
